package oneK.round.events

enum class RoundEvent {
    STAGE_STARTED,
    STAGE_ENDED,
    ROUND_STARTED,
    ROUND_ENDED,
    BOMB_ACTIVATED,
    ROUND_RESTARTED,
    BID_CHANGED,
    TRIUMPH_CHANGED,
    CARD_PLAYED,
    PLAYER_CHANGED,
    TALON_PICKED,
    TALON_DISTRIBUTED
}